import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavbarDesktop from '@/app/component/navbar/navbarDesktop'
import NavbarMobileDeskto from '@/app/component/navbar/navbarMobileDesktop'
import FooterDesktop from '@/app/component/footer/footerDesktop'
import FooterMobileDesktop from '@/app/component/footer/footerMobileDesktop'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Teknisiade2025",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen `}
      >
        {/*<NavbarDesktop />  */}
        <NavbarMobileDeskto />
        <main className="flex-grow">{children}</main>
        {/*<FooterDesktop />*/}
        <FooterMobileDesktop/>
      </body>
    </html>
  );
}
