import { Geist, Geist_Mono, Sofia_Sans_Condensed } from "next/font/google";
import "./globals.css";
import NavbarDesktop from '@/app/component/navbar/navbarDesktop'
import NavbarMobileDeskto from '@/app/component/navbar/navbarMobileDesktop'
import FooterDesktop from '@/app/component/footer/footerDesktop'
import FooterMobileDesktop from '@/app/component/footer/footerMobileDesktop'

const sofia = Sofia_Sans_Condensed({
  variable: "--font-sofia",
  subsets: ["latin"],
  weight: ["400", "500", "700"], 
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Teknisiade2025",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${sofia.variable} antialiased`}
      >
        {/*<NavbarDesktop />  */}
        <NavbarMobileDeskto />
        <main className="flex-grow">{children}</main>
        {/*<FooterDesktop />*/}
        <FooterMobileDesktop/>
      </body>
    </html>
  );
}